FROM golang:1.24 AS builder

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
ENV CGO_ENABLED=1
RUN go build -tags=prod -o app ./cmd/telegram/main.go

FROM golang:1.24

WORKDIR /app

COPY --from=builder /app/app /app/
COPY .env /app/.env

CMD ["/app/app"]