services:
    telegram:
        build:
            context: .
            dockerfile: Dockerfile.telegram
        restart: unless-stopped
        networks:
            - services
            - storage
    discord:
        build:
            context: .
            dockerfile: Dockerfile.discord
        restart: unless-stopped
        networks:
            - lowlatency-net
            - services
            - storage
        cap_add:
            - SYS_NICE
        ulimits:
            rtprio: 99

networks:
    services:
        external: true
    storage:
        external: true
    lowlatency-net:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1400
