FROM golang:1.24-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64 \
    CC=gcc \
    go build -tags=prod -ldflags '-extldflags "-static"' -o app ./cmd/telegram/main.go

FROM alpine

WORKDIR /app

COPY --from=builder /app/app /app/
COPY .env /app/.env

CMD ["/app/app"]