services:
    telegram:
        build:
            context: .
            dockerfile: Dockerfile.telegram
        restart: always
        networks:
            - services
            - storage
    discord:
        build:
            context: .
            dockerfile: Dockerfile.discord
        restart: always
        networks:
            - services
            - storage

networks:
    services:
        external: true
    storage:
        external: true
